model_id: "gpt-4o-mini"
temps: [0.0]
samples_per_item:
  "0.0": 1
max_new_tokens:
  closed_book: 1024
  open_book: 1024
top_p: 1.0
top_k: 50
stop: []
sizes:
  closed_book_max_items: null
  open_book_max_items: 100
  triviaqa_max_items: null
  nq_open_max_items: null
  squad_v2_max_items: null
paths:
  raw_dir: "data/raw"
  prepared_dir: "data/prepared"
  batch_inputs_dir: "data/batch_inputs"
  results_dir: "results"
  reports_dir: "reports"
  run_manifest: "results/run_manifest.json"
  experiments_dir: "experiments"
pricing:
  input_per_million: 0.15
  output_per_million: 0.60
  batch_discount: 0.5
use_batch_api: true
stats:
  bootstrap_samples: 1000
  permutation_samples: 1000
  random_seed: 1337
  enable_permutation: true
  enable_fdr: true
  risk_thresholds: [0.0, 0.25, 0.5, 0.75, 1.0]
  tost_alpha: 0.05
  tost_margins:
    em: 0.01
    f1: 0.01
unsupported:
  strategy: overlap
  threshold: 0.5
  min_token_overlap: 0.6
prompt_sets:
  default:
    control: config/prompts/control_system.txt
    treatment: config/prompts/treatment_system.txt
default_prompt_set: default
sweep: null
